src/NetBaires/Models/Meetup/Sponsor.cs
namespace NetBaires.Models.Meetup
{
    public class Sponsor
    {
        public string name { get; set; }
        public string image_url { get; set; }
        public string url { get; set; }
        public string info { get; set; }
    }
}

src/NetBaires/Pages/Events/Detail.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NetBaires.Data;
using NetBaires.Models;
using NetBaires.Services;

namespace NetBaires.Pages.Events
{
    public class DetailModel : PageModel
    {
        public EventViewModel Event { get; set; } = new EventViewModel();
        public List<MemberViewModel> Speakers { get; set; } = new List<MemberViewModel>();
        public List<PhotoViewModel> Photos { get; set; }

        private readonly IMeetupService _meetupService;
        private readonly ApplicationDbContext _context;

        public DetailModel(IMeetupService meetupService, ApplicationDbContext context)
        {
            _meetupService = meetupService;
            _context = context;
        }

        public async Task OnGet(string id)
        {
            await GenerateDataToShow(id);
        }

        private async Task GenerateDataToShow(string id)
        {
            Photos = (await _meetupService.GetPhotos(new List<string> { id }, 50)).Select(x => new PhotoViewModel(x)).ToList();

            var eventDetail = await _meetupService.GetEventDetail(id);
            var eventDb = _context.Events.Include(x => x.Speakers).FirstOrDefault(x => x.Id == id);
            Event = new EventViewModel(eventDetail);
            Speakers = new List<MemberViewModel>();
            if (eventDb != null)
                foreach (var eventDbSpeaker in eventDb.Speakers)
                    Speakers.Add(new MemberViewModel(await _meetupService.GetMemberDetail(eventDbSpeaker.SpeakerId)));

        }

    }
}

src/NetBaires/Pages/Speakers/Detail.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NetBaires.Data;
using NetBaires.Models;
using NetBaires.Services;

namespace NetBaires.Pages.Speakers
{
    public class DetailModel : PageModel
    {
        [BindProperty]
        public MemberViewModel Speaker { get; set; } = new MemberViewModel();
        [BindProperty]
        public List<EventViewModel> Events { get; set; } = new List<EventViewModel>();

        private readonly IMeetupService _meetupService;
        private readonly ApplicationDbContext _context;

        public DetailModel(IMeetupService meetupService, ApplicationDbContext context)
        {
            _meetupService = meetupService;
            _context = context;
        }

        public async Task OnGet(string id)
        {
            await GenerateDataToShow(id);
        }

        private async Task GenerateDataToShow(string id)
        {
            var eventDetail = await _meetupService.GetMemberDetail(id);
            var speakerDb = _context.Speakers.Include(x => x.Events)
                                             .ThenInclude(x=> x.Event)
                                             .FirstOrDefault(x => x.Id == id);
            Speaker = new MemberViewModel(eventDetail);
            Events = new List<EventViewModel>();
            foreach (var eventDbSpeaker in speakerDb.Events?.OrderByDescending(x=> x.EventId))
                Events.Add(new EventViewModel(eventDbSpeaker.Event));

        }
    }
}

src/NetBaires/Pages/Sponsors/Detail.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using NetBaires.Data;
using NetBaires.Models;
using NetBaires.Services;

namespace NetBaires.Pages.Sponsors
{
    public class DetailModel : PageModel
    {
        public List<EventViewModel> Events { get; set; } = new List<EventViewModel>();
        public List<PhotoViewModel> Photos { get; set; }
        public SponsorViewModel Sponsor { get; set; }


        private readonly IMeetupService _meetupService;
        private readonly ApplicationDbContext _context;

        public DetailModel(IMeetupService meetupService, ApplicationDbContext context)
        {
            _meetupService = meetupService;
            _context = context;
        }

        public async Task OnGet(string id)
        {
            await GenerateDataToShow(id);
        }

        private async Task GenerateDataToShow(string id)
        {
            var events = _context.Events.Include(x => x.Sponsors)
                .ThenInclude(s => s.Sponsor)
                .Where(x => x.Sponsors.Any(s => s.SponsorId == id))
                .ToList();
            var groupDetail = (await _meetupService.GroupDetail()).results[0];
            var sponsor = _context.Sponsors.Where(x => x.Name == id).FirstOrDefault();
            Sponsor = (await _meetupService.GroupDetail()).results[0].sponsors?.Select(x => new SponsorViewModel(x, sponsor))
                .ToList()
                .FirstOrDefault(s => s.Name == id);
            Events = events?.Select(x => new EventViewModel(x)).ToList();

            Photos = (await _meetupService.GetPhotos(events.Select(x => x.Id).ToList(), 50)).Select(x => new PhotoViewModel(x)).ToList();
        }

    }
}

src/NetBaires/ViewComponents/ContactUsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NetBaires.Models;

namespace NetBaires.ViewComponents
{
    public class ContactUsViewComponent : ViewComponent
    {
        [BindProperty]
        public ContactUsViewModel ContactUs { get; set; } = new ContactUsViewModel();
        public ContactUsViewComponent()
        {

        }

        public IViewComponentResult Invoke()
        {
            return View(ContactUs);
        }
    }
    public class BreadcrumbViewComponent : ViewComponent
    {
        public BreadcrumbViewModel Breadcrumb { get; set; }
        public BreadcrumbViewComponent()
        {

        }

        public IViewComponentResult Invoke(BreadcrumbViewModel breadcrumbViewModel)
        {
            return View(breadcrumbViewModel);
        }
    }

    public class BreadcrumbViewModel
    {
        public string Title { get; set; }
        public string ActualPage { get; set; }

        public BreadcrumbViewModel(string title, string actualPage)
        {
            Title = title;
            ActualPage = actualPage;
        }
    }


}

src/NetBaires/ViewComponents/EventsListViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NetBaires.Models;
using NetBaires.Services;

namespace NetBaires.ViewComponents
{
    public class EventsListViewComponent : ViewComponent
    {
        private readonly IMeetupService _meetupService;

        public EventsListViewComponent(IMeetupService meetupService)
        {
            _meetupService = meetupService;
        }

        public async Task<IViewComponentResult> InvokeAsync(List<EventViewModel> events)
        {
            return View(events);
        }
    }
}

src/NetBaires/Pages/Sponsors/Detail.cshtml
@page
@using ViewComponents
@model Sponsors.DetailModel
@await Component.InvokeAsync("Breadcrumb", new BreadcrumbViewModel(@Model.Sponsor.Name, "Sponsor"))

<main>
    <div class="lgx-post-wrapper">
        <!--News-->
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <article>
                            <header>
                                <figure>
                                    <img style="width: 320px;" src="@Model.Sponsor.LogoUrlHigh" alt="New" />
                                </figure>
                                <div class="text-area">
                                    <div class="speaker-info">
                                        <a href="@Model.Sponsor.Url">
                                            <h1 class="title">
                                                @Model.Sponsor.Name
                                        </h1>
                                        <h4 class="subtitle">@Model.Sponsor.Url</h4>
                                    </a>
                                </div>
                                @*<ul class="list-inline lgx-social">
                                        <li><a href="@Model.Speaker.Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                        <li><a href="@Model.Speaker.Facebook"><i class="fa fa-facebook-f" aria-hidden="true"></i></a></li>
                                        <li><a href="@Model.Speaker.Linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                        @*<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                                            <li><a href="@Model.Speaker.Facebook"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                    </ul>*@
                            </div>
                        </header>
                        <section>
                            <p>
                                @Model.Sponsor.Info
                            </p>
                            @*<blockquote>
                                    <p>Suspendisse hendrerit et sapien ut pretium. Aenean nulla ipsum, facilisis eu porta non, rutrum sit amet nibh. Quisque id diam feugiat, pharetra arcu eget, bibendum tortor. </p>
                                    <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
                                </blockquote>*@
                        </section>
                        @*<footer>
                                <div class="row">
                                    <div class="col-xs-12">
                                        <h4 class="title">Share</h4>
                                        <div class="lgx-share">
                                            <ul class="list-inline lgx-social">
                                                <li><a href="@Model.Speaker.Twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                                <li><a href="@Model.Speaker.Facebook"><i class="fa fa-facebook-f" aria-hidden="true"></i></a></li>
                                                <li><a href="@Model.Speaker.Linkedin"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </footer>*@
                    </article>
                </div>
            </div>
        </div><!-- //.CONTAINER -->
    </section>
    <!--News END-->
</div>
</main>
<section>
    <div id="lgx-news" class="lgx-news">
        <div class="lgx-inner">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="lgx-heading">
                            <h2 class="heading">Eventos en los que @Model.Sponsor.Name nos apoyo</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    @await Component.InvokeAsync("EventsList", Model.Events)
                </div>
            </div><!-- //.CONTAINER -->
        </div><!-- //.INNER -->
    </div>
</section>

<section>
    <div id="lgx-photo-gallery" class="lgx-gallery-popup lgx-photo-gallery-normal lgx-photo-gallery-black">
        <div class="lgx-inner">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="lgx-heading lgx-heading-white">
                            <h2 class="heading">Fotos en las que participo @Model.Sponsor.Name</h2>
                            @*<h3 class="subheading">Algunas fotos de los eventos pasados!!</h3>*@
                        </div>
                    </div>
                </div>
                @await Component.InvokeAsync("PhotosPreview", Model.Photos)
            </div>
        </div>
    </div>
</section>